language: node_js
node_js:
  - "stable"
cache:
directories:
  - "node_modules"
addons:
  chrome: stable
install:
  - npm install
before_script:
  - npm install coverage
  - npm install -g nyc  
script:
  - npm run coverage
  - npm run test

# after_success:
# - npm run coverage
