language: node_js
node_js:
  - "stable"
cache:
directories:
  - "node_modules"
addons:
  chrome: stable
# install:
#   - npm install
before_script:
  - npm install coveralls
  - npm install -g nyc  
script:
  # - npm run coverage
  - npm run test
after_script:
  - npm run coverage
# after_success:
# - npm run coverage



