language: node_js
node_js:
  - "stable"
cache:
directories:
  - "node_modules"
addons:
  chrome: stable
install:
  - npm install
  
before_script:
  - npm install coverage
  - npm install -g nyc  
after_script:
  - npm run coverage
script:
  - npm run test
  - npm run coverage


# after_success:
# - npm run coverage
