const userData = {
  signup: [{
    firstName: 'mwafrika',
    lastName: 'josue',
    email: 'mwafrikajosue@gmail.com',
    password: '123',
    gender: 'male',
    jobRole: 'IT manager',
    department: 'IT',
  },
  {
    firstName: 'junior',
    lastName: 'jose',
    email: 'mwafrikajosue@gmail.com',
    password: '123',
    gender: 'femail',
    jobRole: 'IT officer',
    department: 'IT',
    address: 'Goma',
  },
  {
    firstName: 'junior',
    lastName: 'jose',
    email: 'mwafrikajosuegmail.com',
    password: '123',
    gender: 'female',
    jobRole: 'IT officer',
    department: 'IT',
    address: 'Gisenyi',
  },
  {
    firstName: '',
    lastName: 'jose',
    email: 'mwafrikajosuegmail.com',
    password: '123',
    gender: 'female',
    jobRole: 'IT officer',
    department: 'IT',
    address: 'Kinshasa',
  },
  {
    firstName: 'sakina',
    lastName: '',
    email: 'frikajosu@gmail.com',
    password: '123',
    gender: 'female',
    jobRole: 'IT officer',
    department: 'IT',
    address: 'Ghana',
  },
  {
    firstName: 'jolie',
    lastName: 'jose',
    email: '',
    password: '123',
    gender: 'female',
    jobRole: 'IT officer',
    department: 'IT',
    address: 'Burundi',
  },
  {
    firstName: 'soki',
    lastName: 'jose',
    email: 'rikajosuegmail.com',
    password: '',
    gender: 'female',
    jobRole: 'IT officer',
    department: 'IT',
    address: 'Walikale',
  },
  {
    firstName: 'jiji',
    lastName: 'jose',
    email: 'mwafrik@gmail.com',
    password: '123',
    gender: '',
    jobRole: 'IT officer',
    department: 'IT',
    address: 'Soudan',
  },
  {
    firstName: 'jojo',
    lastName: 'jose',
    email: 'mwafrajo@gmail.com',
    password: '123',
    gender: 'female',
    jobRole: '',
    department: 'IT',
    address: 'Bukavu',
  },
  {
    firstName: 'regis',
    lastName: 'jose',
    email: 'kakule@gmail.com',
    password: '123',
    gender: 'male',
    jobRole: 'IT officer',
    department: '',
    address: 'Washington',
  },
  {
    firstName: 'heri',
    lastName: 'jose',
    email: 'alin@gmail.com',
    password: '123',
    gender: 'female',
    jobRole: 'IT officer',
    department: 'IT',
    address: '',
  },
  {
    firstName: '7887677',
    lastName: 'jose',
    email: 'kasole@gmail.com',
    password: '123',
    gender: 'female',
    jobRole: 'IT officer',
    department: 'IT',
    address: 'Maniema',
  },
  {
    firstName: 'senga',
    lastName: '88887',
    email: 'kasole2@gmail.com',
    password: '123',
    gender: 'female',
    jobRole: 'IT officer',
    department: 'IT',
    address: 'Maniema',
  },
  {
    firstName: 'Jules',
    lastName: 'jose',
    email: 'Jumbo1@gmail.com',
    password: '123',
    gender: '12345',
    jobRole: 'IT officer',
    department: 'IT',
    address: 'Maniema',
  },
  ],
  login: [
    {
      email: 'mwafrikajosu@gmail.com',
      password: '123',
    },
    {
      email: 'mwafrikajosue@gmail.com',
      password: '123',
    },
    {
      email: '',
      password: '1234',
    },
    {
      email: 'mwafri@gmail.com',
      password: '',
    },
  ],
};
export default userData;
